// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjCaf4ca__ruFk34ghXzZG8FWyLsZFG_s',
    appId: '1:949173303262:web:ae4e4166804055de940f4f',
    messagingSenderId: '949173303262',
    projectId: 'app-sinh-vien-b6ea4',
    authDomain: 'app-sinh-vien-b6ea4.firebaseapp.com',
    storageBucket: 'app-sinh-vien-b6ea4.firebasestorage.app',
    measurementId: 'G-0F3G63ZY5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV15WumXtOlYdgjOrXJHTs8sgNdAZvDt4',
    appId: '1:949173303262:android:c3a064a5a60523b2940f4f',
    messagingSenderId: '949173303262',
    projectId: 'app-sinh-vien-b6ea4',
    storageBucket: 'app-sinh-vien-b6ea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf3N9zu2w_5BQ6_gAsEChsiyXcKXU3hWA',
    appId: '1:949173303262:ios:11b556e0db9365b6940f4f',
    messagingSenderId: '949173303262',
    projectId: 'app-sinh-vien-b6ea4',
    storageBucket: 'app-sinh-vien-b6ea4.firebasestorage.app',
    iosBundleId: 'vn.edu.appsinhvien.appSinhVien',
  );
}
